### ISSUE TITLE
Dockerfile Downloads

### ISSUE THREAD

**Issue by kagestrife** [flaviobarros/shiny-wordcloud#9]
This is more of a question, rather than an issue. I want to ask some things about the dockerfile you have created, since I started using docker only a few days ago and your example is the only viable on the internet at the moment, regarding R shiny and how it can be used with docker. 

a) Why are you using r-base instead of, lets say, rocker/shiny? Are there differences? Is there a particular reason you picked the first?
b) Why are you downloading debian files? Are they needed for running the containers? Are they connected with the proper run of the r shiny apps? If so, how?
c) In your example you are exposing the port 80 and you have created a conf file which listens to the same port. Can you give more info or similar examples about the .conf file? Can you explain the last CMD command you are giving in the Dockerfile?

I hope Im not an annoyance, thanks in advance and am looking forward to your replies.

**Comment by flaviobarros** [comment]
Let's start with the easier ones:

**c) In your example you are exposing the port 80 and you have created a conf file which listens to the same port. Can you give more info or similar examples about the .conf file? Can you explain the last CMD command you are giving in the Dockerfile?**

You can think of a docker image as a linux box (a docker file is just a "recipe" to create docker images). You can expose or block some ports, like 80, and you can have an app that USES this port or NOT. So we have to expose 80 in the Dockerfile but we have to tell to shiny server to listen to 80 too.

Regarding other examples of configurations files for Shiny I suggest you to take a look at the official documentation of [Shiny](http://docs.rstudio.com/shiny-server/#default-configuration).

**a) Why are you using r-base instead of, lets say, rocker/shiny? Are there differences? Is there a particular reason you picked the first?**

Well, this is what is working now. You can try others. I GUESS that should work. In fact I started this dockerfile from [rocker/shiny](https://github.com/rocker-org/shiny/blob/master/Dockerfile).

**b) Why are you downloading debian files? Are they needed for running the containers? Are they connected with the proper run of the r shiny apps? If so, how?**

We need some packages to install the shiny server. You can think of a docker file as the commands you should use on the terminal to install a shiny server and expose the 80 port. Try yourself in a empty VM or in you machine, or even in a interactive docker session.

OBS: Please, if the answer is ok you can close the issue. Feel free to do any more question if needed.

**Comment by kagestrife** [comment]
Hey, thank you for the replies. I've come up with more questions. I have come across many problems trying to use packages from the bioconductor site. What needs to be done, according to their docs, is to run an r script like this:

RUN Rscript -e 'source("http://bioconductor.org/biocLite.R");library(BiocInstaller); biocLite("flowCore", dep = TRUE)'

what i have added to the rocker Dockerfile are these C libraries
libxml2-dev \
    libxml2 \
    mesa-common-dev \
    libglu1-mesa-dev \ 
    freeglut3-dev \
    hdf5-tools \
    libhdf5-openmpi-dev \
    libhdf5-serial-dev 
needed for various packages from CRAN or bioconductor. Still, I get a warning about the rgl http://imgur.com/a/QQ7Bx (no errors though) and when I try to run a simple container i get this
"standard_init_linux.go:175: exec user process caused "exec format error". I am guessing this has to do something with the rgl error I posted.

**Comment by flaviobarros** [comment]
In this case I think the best option is discuss the issue on your own repo.

Could you send me your repo as I can see your code?

**Comment by kagestrife** [comment]
sorry for the delay. On the last matter I got the reply needed. I will close the issue now. Thanks a lot!
